### ISSUE TITLE
RDP & HC

### ISSUE THREAD

**Issue by designgears** [Valkirie/HandheldCompanion#333] opened 2023-01-17 19:11 UTC
When connecting via RDP to my device (Ayaneo 2) HC disables as I would expect, or it's crashing at that point. The problem is when I login on to the device physically HC doesn't enable or crashes at this point.

**Comment by CasperH2O** [comment] 2023-01-18 09:34
Thank you for bringing to to attention, I'll see if I can reproduce it.

**Comment by CasperH2O** [comment] 2023-01-18 11:55
Regrettably, both my Aya devices come with Windows Home edition and thus have no inbound RDP support. Won't be able to test this with VS running HC in debug.

**Comment by designgears** [comment] 2023-01-19 02:09
@CasperH2O I can provide a couple keys if you need.

**Comment by CasperH2O** [comment] 2023-01-20 06:45
> @CasperH2O I can provide a couple keys if you need.

Thank you for the kind offer @designgears , I'll pick this up when I get my Air repaired.

**Comment by CasperH2O** [comment] 2023-03-01 06:11
Shared by DesignGears on Discord: [HandheldCompanion.exe.11908.zip](https://github.com/Valkirie/HandheldCompanion/files/10857665/HandheldCompanion.exe.11908.zip)

**Comment by CasperH2O** [comment] 2023-04-01 05:53
Confirmed to be fixed by @designgears

**Closed by CasperH2O** 2023-04-01 05:53 UTC
Labels: bug
