### ISSUE TITLE
Can't use dpad or -/+ keys of Rog Ally as part of Hotkeys

### ISSUE THREAD

**Issue by felipejfc** [Valkirie/HandheldCompanion#640] opened 2023-06-21 22:19 UTC
The hotkeys page is not recognizing the - and + keys, or the dpad in the ally. I wanted for example to replicate the same one as armory crate to open virtual keyboard, (3+dpad up) but because the screen doesn't recognize dpad its impossible.

**Comment by felipejfc** [comment] 2023-06-21 22:38
managed to get it working by disabling the controller in the home. now I'm trying to figure out how to map secondary actions like in armory crate. are there ways to do it?

**Comment by CasperH2O** [comment] 2023-06-22 06:08
@felipejfc HC does not support holding one button and then pressing different ones in terms of a hotkey. There is only hold single or multiple buttons and click single or multiple buttons.

**Comment by felipejfc** [comment] 2023-06-22 14:08
I think you're headed the right direction with this project, congrats. One feedback though is that right now armory crate way of dealing with profiles and hotkeys is working much better than HC, I think this is expected since you just added support for the ally and is trying to support multiple devices at the same time.
I suggest that you consider disabling some functionality while keeping others. e.g. I would like to continue using your autotdp implementation, however I would like HC not to mess with my controller in any way so that AC keeps doing it job

**Comment by CasperH2O** [comment] 2023-06-29 08:38
@felipejfc you can disable all of HCs controller related features by:
- On the main GUI controller page, disconnect the virtual controller
- On the main GUI controller page, unhide the physical controller
- Bottom left of the main GUI, stop service followed by remove service

Happy gaming!

**Comment by CasperH2O** [comment] 2023-08-09 09:22
Closing as this is not a bug but simply the way it's currently implemented. Additional questions have been answered.

**Closed by CasperH2O** 2023-08-09 09:22 UTC
Labels: wontfix
