### ISSUE TITLE
Gyro curve / button bindings short and long press

### ISSUE THREAD

**Issue by dkswedens** [Valkirie/HandheldCompanion#790] opened 2023-10-06 08:16 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [X ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
ROG Ally

**Handheld Companinion Version**
0.18.0.3

**Describe the bug**
Altering the gyro curve HC occassionally crashes, more often than not.
Adding a long press button in this example (xbox guide) to view button on rog ally, the short press action doesn't always register.

**To Reproduce**
Try changing the gyro curve
try different long / short press buttons and see the short press action doesnt always register

**Comment by CasperH2O** [comment] 2023-10-10 06:23
@dkswedens thanks for reporting. Please do not create a single ticket for two different problems, that makes administration difficult.

The gyro curve will be most likely replaced/updated with the new graph that is being built for fan control.

I'll check on my ROG Ally if I can reproduce your short press action problem.

**Comment by CasperH2O** [comment] 2023-11-13 19:52
Can't reproduce the gyro curve issue.
Can reproduce the long press issue. Define a hotkey with short press (A), the try to define another hotkey with long press (A), it won't register, but trying to define again will register a short as long.

**Comment by CasperH2O** [comment] 2023-11-28 19:58
Long press issue has need fixed.

**Comment by CasperH2O** [comment] 2023-11-28 20:01
Reproduced gyro curve crash, used gamepad navigation to select and apply the presets.

![image](https://github.com/Valkirie/HandheldCompanion/assets/14330834/9f5b70ae-9b67-4ee8-b4d0-96e9af761adb)

**Comment by Valkirie** [comment] 2023-11-28 20:30
Oh yeah, modifying the gyro array while gyro is enabled means we're trying to modify the array while it's being read. We can either set the array to some form of concurrent stuff or be smarter here.

**Comment by CasperH2O** [comment] 2023-11-30 10:26
@Valkirie I'm tempted to leave the gyro curve crash bug for now until such a time when the cosmetic issues of the fan curve have been fixed and we can port the code and just update the UI. 

Then again, I really love this type of graph and it even includes the gyro motion highlight. ❤️

**Comment by CasperH2O** [comment] 2024-06-14 12:53
As the button bindings was also fixed, I'm closing this one. Thanks for reporting these in @dkswedens

**Closed by CasperH2O** 2024-06-14 12:53 UTC
Labels: Bug, Minor
