### ISSUE TITLE
Game Profiles changing the Controller Type

### ISSUE THREAD

**Issue by Bagboii** [Valkirie/HandheldCompanion#847] opened 2023-11-24 19:04 UTC
Single/Multi-App Profiles that detect Games do not have a Feature to change Emulated Controller Type yet.

It would be useful to make it automatic, so that you can hop into any game and not fiddle around with changing controller settings, to get compatibility in games that require either Dualshock (Gyro-based Games and Emulators with Motion Control) or XInput (Games that do not recognize DualShock)

**Comment by CasperH2O** [comment] 2023-11-28 13:26
Thank you for your suggestion! This is a duplicate of #57 which you will be happy to know is actively being worked on.

**Closed by CasperH2O** 2023-11-28 13:26 UTC
Labels: enhancement
