### ISSUE TITLE
QuickTools blank and not getting Game .exe for profile creation

### ISSUE THREAD

**Issue by yauhenbarysik** [Valkirie/HandheldCompanion#521] opened 2023-05-02 09:25 UTC
Hello. First of all, you have a really nice software and big thank you for that. But unfortunately, it has really pretty critical bug which stops you from using it to full potential (tweaking performance settings like TDP, Refresh Rate and saving it to separate profile).

Steps:
1. Launch HC
2. Disable Desktop Layout (doesn't matter actually, that just reduces input doubling via controller)
3. Launch some game (in my case that was Cyberpunk 2077)
4. Summon QuickTools via hotkey (in my case its 3dots button)
5. Open Profiles
6. Close QuickTools (via hotkey)
7. Open it again

Expected Result: Quicktools should get your game process and not minimize game. Re-opening QuickTools shouldn't make any difference
Actual Result: Quicktools just gets steam process except game itself. Re-opening QuickTools makes it blank (solved by clicking on HC icon in the tray). Each time QuickTools launched game minimizes (I guess that is the issue why it cannot get game process for profiling). 

Environment: Latest Windows 10 22H2, HC version 0.15.1.1

**Comment by yauhenbarysik** [comment] 2023-05-02 09:35
Btw, double-checked that with both Windowed Mode and Borderless Windowed Mode (and Fullscreen as well) - same issue. That cases game to minimize. And re-summoning QuickTools in game makes QuickTools blank and requires launcing HC from tray to "fix" blank window of QuickTools.

**Comment by Havner** [comment] 2023-05-02 11:28
Speaking only about game minimizing. From my experience some games (even in borderless) minimize when they loose focus. That's not really HC issue I think.

As a workaround you can make sure there are no other windows on the screen. In such case when game minimizes quicktools should still see the game's profile.

In any case you don't even need to have quicktools to see the current game. The performance tab which you are after is not tied to game profile. TDP/refresh rates those are global settings. So they will work regardless of what profile is active.
TDP has per profile override but you can configure that in the main window for a profile. No need to use quicktools for that if that is impossible due to the situation you described above.

**Comment by Havner** [comment] 2023-05-03 10:43
About the black issue, I have an idea. As you have a reproducible way of triggering this would you be willing to test something?

https://www.youtube.com/watch?v=7HMAE1sKRCc

As Windows Steam Deck drivers can be poor, try to install those and test whether you can reproduce the black issue.

**Comment by Havner** [comment] 2023-05-03 11:25
Blank, black, empty, whatever. Depends on what is below as the window can be partly transparent. So it can actually be black.

I did not ask you to test the driver because of any game.

The UI is accelerated. It's also composited (if you know the term). This is all stuff that GPU driver is doing. And the fact that transparent window stays empty after graphical context switching might be a manifestation of a bug in the graphics driver.

**Comment by Havner** [comment] 2023-05-05 11:05
There are issues with games:
https://steamcommunity.com/app/1675200/discussions/1/3761101693157174808/

We don't know what is the good practice (regarding the readme) as we don't know the cause of the issue. This bug would be closed if we did. The driver is just a suggestion to test as you can reliably reproduce this. I can't. It happens for me from time to time, but not reliably.

**Comment by Havner** [comment] 2023-05-05 11:22
First of all I'm not a WPF UI programmer. I'm not responsible for any UI parts here. @Valkirie would have to speak here.
Second of all, the UI elements seem to be loaded. I've managed to at least click on the closing X when that happened (despite not being visible). From what I can see this is not a simple issue of not displaying UI elements. Something is bugged on a much lower level with actually redrawing the whole buffer of that particular window.

**Comment by CasperH2O** [comment] 2023-05-17 09:16
I'm surprised to read that setting the game to Windowed Mode or Borderless Windowed Mode still makes it minimize when QuickTools is opened. This is not a very common issue luckily. I recommend you create and configure the profile through the main GUI instead. 

I'd like to play Cyberpunk 2077 some day, will check QuickTools then.

**Comment by CasperH2O** [comment] 2023-05-31 11:37
@yauhenbarysik we released 0.16.0.4 and will shortly release 0.16.0.5, could you check if you're still experiencing this issue? Several improvements and fixes have been made in this regard.

**Comment by CasperH2O** [comment] 2023-06-20 07:36
@yauhenbarysik I no longer observe this problem on a regular basis, can you confirm?

**Comment by CasperH2O** [comment] 2023-08-08 12:20
No response from original issue creator. Can no longer reproduce myself, several updates have been made to this code. Closing ticket.

**Closed by CasperH2O** 2023-08-08 12:20 UTC
Labels: bug
