### ISSUE TITLE
HC crashes on resolution change

### ISSUE THREAD

**Issue by m33ts4k0z** [Valkirie/HandheldCompanion#841] opened 2023-11-20 21:06 UTC
**Device manufacturer**
- [*] LENOVO

**Device model**
Legion Go

**Handheld Companinion Version**
0.19.0.3 (Beta 5)

**Describe the bug**
When changing the resolution either through HC, using a script or using the Windows display settings, HC crashes.

**To Reproduce**
Just try to change the resolution in any way. The HC icon will still be in the system tray but if you open it, it will look like its searching for the controller but it will eventually crash. That subroutine (trying to get the controller) might be connected to the crash?

Additional info: The ambilight could be connected to this but it's not. The same behavior occurs even when the LEDs are turned off.

**Expected behavior**
HC shouldn't be affected by a resolution change.

**Logs file**
[2023-11-20_21-59-39dumpfile.dmp](https://github.com/Valkirie/HandheldCompanion/files/13419421/2023-11-20_21-59-39dumpfile.dmp)
[HandheldCompanion-20231120.log](https://github.com/Valkirie/HandheldCompanion/files/13419457/HandheldCompanion-20231120.log)

**Comment by NightHammer1000** [comment] 2023-11-20 21:09
In addition to the Dump. Also add the Log file which can be found in the Programs Install Directory.

**Comment by m33ts4k0z** [comment] 2023-11-20 21:11
Sure I forgot about that log file. I added it to the bug report 😁

**Comment by CasperH2O** [comment] 2023-11-23 10:40
Thank you. Can reproduce this on the ROG Ally.

**Comment by CasperH2O** [comment] 2023-12-01 10:31
Unable to reproduce with latest EA main branch. Tried two different devices (Ayaneo 2021, ROG Ally), changed resolutions through Windows, on both handheld and external monitor, opened games that went fullscreen and changed resolution.

Closing.

**Closed by CasperH2O** 2023-12-01 10:31 UTC
Labels: bug
