### ISSUE TITLE
Game minimized when opening quick menu - ROG ALLY

### ISSUE THREAD

**Issue by gogomimigo** [Valkirie/HandheldCompanion#670] opened 2023-06-30 00:48 UTC
Hello. I installed HC and closed AC before starting HC. I set a hotkey to open the quick menu but whenever I'm in game and press the hotkey, the game will minimized and it will distort the whole desktop. The quick menu pops up but it kinda messes up the whole experience. Is there a workaround for this?

**Comment by trippyone** [comment] 2023-06-30 04:45
@CasperH2O duplicate of #630

**Comment by CasperH2O** [comment] 2023-07-01 11:01
@gogomimigo , the work around for this is to set games to windowed maximized or borderless fullscreen.

Closing because of duplicate.

**Closed by CasperH2O** 2023-07-01 11:01 UTC
