### ISSUE TITLE
DS4 layout config, add touchpad click press

### ISSUE THREAD

**Issue by MickeyPadge** [Valkirie/HandheldCompanion#706] opened 2023-07-11 18:34 UTC
Be great if when configuring Sony DS4 controller layout, we could have the touchpad press (click) as an option. As Diablo 4 (for example) has this button used as an unmappable selection.

**Comment by GnawtyVeritech** [comment] 2023-08-08 06:28
Just wanted to write to support this feature.

**Comment by CasperH2O** [comment] 2023-10-30 12:20
Duplicate of #799

**Closed by CasperH2O** 2023-10-30 12:20 UTC
Labels: enhancement
