### ISSUE TITLE
Waking up from sleep, connecting & disconnecting external external monitor crashes HC on Steam Deck.

### ISSUE THREAD

**Issue by Quenchster100** [Valkirie/HandheldCompanion#378] opened 2023-02-23 14:38 UTC
My Steam Deck runs Windows 11. Any temporary fixes for these? It's pretty annoying especially since I do both of these things all the time that causes HC to crash.

- If I wake my Steam Deck from sleep, HC first appears in my sys tray and never closes but it also doesn't work. If I double tap it in the sys tray to open it, it then crashes. I have to then reopen it to use it. I have to double tap it on the sys tray to crash it or go into task manager to kill it every time after waking from sleep before I can reopen the process.

- If I connect or disconnect an external monitor, HC crashes. However, unlike the above issue, it fully hard crashes without me having to interact with it in the sys tray first. Again, I have to reopen it. #

**Comment by CasperH2O** [comment] 2023-02-23 15:03
@Quenchster100 thanks for reporting in, sorry to hear about your troubles. In order to (possibly) fix it, we need some more information, can you help with that?

Please try to reproduce this issue with a debug build, it will contain more log info. You can get it here: 

https://github.com/Valkirie/HandheldCompanion/releases/download/0.14.2.0/Handheld.Companion-Debug-net7.0-0.14.2.0.exe

Then find the latest crash dump file in C:\Users\<username>\Documents\HandheldCompanion\dumps 
And share it here. 

You'll have to reproduce both crashes for separate .dmp files.

**Comment by DennisTarr** [comment] 2023-02-25 16:55
Can confirm. If I disconnect the USB hub from my Steam Deck HhC just closes down.

**Comment by CasperH2O** [comment] 2023-02-25 17:12
@DennisTarr thanks for letting us know. To take any step in resolving this, could you help provide the crash dump file? Instructions can be found above.

**Comment by DennisTarr** [comment] 2023-02-25 22:45
[HandheldCompanion.exe.5988.zip](https://github.com/Valkirie/HandheldCompanion/files/10832463/HandheldCompanion.exe.5988.zip)

here the dump after it crashed from undocking

**Comment by DennisTarr** [comment] 2023-03-16 12:43
Seems to be fixed in V15

**Comment by CasperH2O** [comment] 2023-03-16 14:28
Excellent, Thanks for letting us know!

**Closed by CasperH2O** 2023-03-16 14:28 UTC
Labels: bug
