### ISSUE TITLE
ALLy : After using macro key (M1 or M2)   the (3) input stays triggered.

### ISSUE THREAD

**Issue by azodev** [Valkirie/HandheldCompanion#798] opened 2023-10-25 18:12 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [x] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Ally Z1E

**Handheld Companinion Version**
0.18.0.4

**Describe the bug**
After using macro key (M1 or M2)   the (3) input stays triggered, which make HC hotkey  not working, when remapping hotkeys, like long press of start key, it registers (3)+start (long), instead of just start (long).

**To Reproduce**

**Expected behavior**
no ghost input from macro keys. 0.18.0.3 is working I reverted to try, and no issues.

**Screenshots**

**Comment by CasperH2O** [comment] 2023-10-25 18:30
Can reproduce, will investigate.

**Comment by ibrahimqatar** [comment] 2023-10-26 03:59
I can confirm I have the same issue, drove me crazy and I thought there was something wrong with my Rog Ally..

**Comment by CasperH2O** [comment] 2023-10-26 07:39
Fixed by @Valkirie in release 0.18.0.5. Please update accordingly. 🙂

**Comment by ibrahimqatar** [comment] 2023-10-26 11:54
> Fixed by @Valkirie in release 0.18.0.5. Please update accordingly. 🙂 

Setting the button is fine now, but it the menu doesn't show up unless I keep pressing the combination several times.

It used to work from the first try on 0.18.0.3

**Comment by CasperH2O** [comment] 2023-10-30 12:10
Closing as duplicate of #809

**Closed by CasperH2O** 2023-10-30 12:10 UTC
Labels: bug
