### ISSUE TITLE
feature request: remappable left and right mouse buttons.

### ISSUE THREAD

**Issue by xt234** [Valkirie/HandheldCompanion#358] opened 2023-02-12 20:41 UTC
ive been using handheld companion with my steam deck, and a thing ive been missing is the ability to map the mouse buttons to the trackpads. this would be useful, cause itd make it so you dont have to keep lizard mode on when not playing games.

**Comment by Valkirie** [comment] 2023-02-12 20:59
Hey, lizard mode will be replaced by our inputs mapper within the next update. You'll be given the ability to map any buttons or axis to any action: mouse, keyboard, button, axis.

**Comment by xt234** [comment] 2023-02-12 21:02
> Hey, lizard mode will be replaced by our inputs mapper within the next update. You'll be given the ability to map any buttons or axis to any action: mouse, keyboard, button, axis.

thats actually a really helpful feature. tho id still like to keep lizard mode due to it conflicting with some games and apps. the settings app for example freakes out with lizard mode on.

**Comment by xt234** [comment] 2023-02-12 21:03
if i press r2 itll go to a different menu rather then the one i intended to go to.

**Comment by CasperH2O** [comment] 2023-02-13 05:45
Hey @xt234, thanks for reaching out. I'm marking this one a duplicate of #344.

**Closed by CasperH2O** 2023-02-13 05:45 UTC
Labels: enhancement
