### ISSUE TITLE
Monitor won´t turn off -> when HC service is running 

### ISSUE THREAD

**Issue by SuperSailorMoonR** [Valkirie/HandheldCompanion#483] opened 2023-04-16 10:11 UTC
Hi,

while HC service is running my monitor won´t turn off regardless the turn off time or energy mode setting.
I tried it with and without an external monitor attached, same result. 
I tried also setting another performance mode in the quick access menu form HC.

If I stop the HC service then the monitor is turning off accordengly to the time set.

I´m on Steamdeck with windows 10 21H2 and HC 0.15.0.4.

**Comment by CasperH2O** [comment] 2023-08-08 12:22
This might be related to the emulated HID mouse and keyboard, which can also wake the device from sleep at times.

**Comment by CasperH2O** [comment] 2023-11-24 08:45
Tried to reproduce. Switching off the screen after one minute works with both HC running or not. Sleep mode does not seem to work after the timeout, regardless if HC is running or not and with all HID, mouse and keyboard devices having the "Allow this device to wake the computer" setting unticked. Triggering sleep mode from the Start menu does work and the device goes to sleep properly.

This issue seems to be a duplicate of #754, closing.

**Closed by CasperH2O** 2023-11-24 08:45 UTC
Labels: bug
