### ISSUE TITLE
Clicking the hide button will cause the software to flash back

### ISSUE THREAD

**Issue by LyfGinnov** [Valkirie/HandheldCompanion#775] opened 2023-09-05 14:42 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [] ONEXPLAYER
- [x] VALVE

**Device model**
steam deck

**Handheld Companinion Version**

0.18.0.1

**Describe the bug**

Clicking the hide button will cause the software to flash back, After flashing, the software manually starts hide and becomes unhide, but when the software is closed and restarted, it will become hide again

**To Reproduce**
1. Open the Handheld Companinion
2. Click to hide
3. Flash back to desktop
4. Reopen Handheld Companinion,’unhide’will change ‘hide’

**To expected**
Click to ‘hide’ don’t Flash Back to  desktop;
After changing to unhide, do not restore the software to hide next time you start it

**Screenshots**
![343dd3b2ede961bdf2779cf55214ca71](https://github.com/Valkirie/HandheldCompanion/assets/119551714/ebb17be5-cc6e-4955-8579-c00806e987ff)

**Logs file**
If applicable, add logs file stored in your install location, logs folder.

**Comment by CasperH2O** [comment] 2024-01-09 07:43
Closing, this part of the UI and code has been seriously reworked with the new controller manager. Was unable to reproduce this initially.

**Closed by CasperH2O** 2024-01-09 07:43 UTC
Labels: bug
