### ISSUE TITLE
Unresponsive controllers on Fortnite

### ISSUE THREAD

**Issue by TehCrazyCat** [Valkirie/HandheldCompanion#1143] opened 2024-09-10 03:06 UTC
**Device manufacturer**
- [X] VALVE

**Device model**
Steam Deck LCD

**Handheld Companion Version**
0.21.5.4

**Describe the bug**
Button inputs are either laggy or unresponsive when playing Fortnite. The joysticks and triggers feel like they get "stuck" and keep shooting, and moving the character or camera for 1sec after release. Other buttons sometimes do not count as pressed. It feels like if you're playing on cloud with bad internet.
Swapping to desktop mode with Fortnite on background will also cause the mouse emulation to be laggy. Note that this only happens with Fortnite on latest HC version. I tried with both Persona 3 Reload (GP Version) and Minecraft for Windows and it worked fine on both of those games, no issues even after long session times.
Rolling back to previous release (0.21.4.1) fixes all the issues.

**To Reproduce**
1. Use latest version of HC (0.21.5.4)
2. Open Fortnite
3. Nothing else. Even on the lobby the buttons are unresponsive and laggy.

**Expected behavior**
Responsive button inputs like on the previous versions.

**Comment by Heronate08** [comment] 2024-10-27 05:09
I have this issue aswell and it only happens in fortnite

**Comment by Valkirie** [comment] 2024-10-27 05:37
Which type of controller are you emulating?

**Comment by Heronate08** [comment] 2024-10-27 07:44
I'm using the steam deck and im emulating an Xbox controller

**Comment by Taboulet** [comment] 2024-10-27 16:13
Xbox controller too, tho i think it was also kinda buggy on a playstation controller

**Comment by TehCrazyCat** [comment] 2024-11-12 01:03
I can confirm this issue still happens on latest release (0.21.7.0) while emulating a PS4 controller. I guess it also happens with Xbox emulation but I didn't tested. HC hotkeys also broke on latest release but that's a whole different issue.

**Comment by harshhere** [comment] 2024-11-17 00:27
Same issue in Fortnite and Halo MCC. Both of the games are unplayable.

**Comment by Valkirie** [comment] 2024-11-17 06:41
Other games are working fine? I'll have to download fornite to try and reproduce this.

**Comment by harshhere** [comment] 2024-11-17 22:56
Others games seem to work just fine

**Comment by Valkirie** [comment] 2024-12-05 08:27
Can you guys check CPU usage when the issue arise ? I'm starting to wonder if it's a bottleneck issue where CPU is so busy with the game there is not enough resources left for HC to compute controller inputs. I've been playing solo sessions and LEGO Fortnite with no issue on my 8840U.

**Comment by Heronate08** [comment] 2024-12-05 16:11
I don't think it's that because it happens in the lobby for me aswell

**Comment by Valkirie** [comment] 2024-12-05 16:49
Got it. Seams to be Steam Deck specific. I'll try to replicate on my device.

**Comment by Valkirie** [comment] 2024-12-06 07:40
Please give the following build a try: https://1drv.ms/u/s!AleMgLLgxwGJiJpXUw0xLlSC0hZ1bg?e=VdzRot

**Comment by TehCrazyCat** [comment] 2024-12-06 08:41
> Please give the following build a try: https://1drv.ms/u/s!AleMgLLgxwGJiJpXUw0xLlSC0hZ1bg?e=VdzRot. Please note you'll need [NET9](https://dotnet.microsoft.com/fr-fr/download/dotnet/thank-you/runtime-desktop-9.0.0-windows-x64-installer).

I can confirm this build fixed the issue, works flawlessly on a BR match. It even fixed the gyro drift! I'll test it further tomorrow but so far seems the issue is gone for good. Tysm!

**Comment by Valkirie** [comment] 2024-12-06 10:26
Great! I'll publish this release officially tomorrow.

**Comment by Ragunator** [comment] 2024-12-06 17:13
Working perfectly on Halo Infinite as well, thanks :)

**Comment by Valkirie** [comment] 2024-12-06 17:26
To be fair this should be positively impact the gaming experience across all games. Long story short, we've made the task responsible for reading inputs from the device a high priority. So when the device has to allocate ressources to a process and its tasks, this one will always come first.

**Comment by Valkirie** [comment] 2024-12-06 17:28
Fixed with forthcoming release. A beta build is available higher in the comments.

**Closed by Valkirie** 2024-12-06 17:28 UTC
Labels: Bug
