### ISSUE TITLE
Multiple Game Modes swappable in Quick tools

### ISSUE THREAD

**Issue by 1xLife** [Valkirie/HandheldCompanion#808] opened 2023-10-29 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Some games, like Sims 4, have far too many keys to map onto some controllers due to a limited amount of buttons

**Describe the solution you'd like**
Ideally, renamable game modes swappable via quicktools. So Explore and Build, or whatever the user wants. Ideally this can be set per game, like default profiles can be.

**Describe alternatives you've considered**
Alternatively... Probably an option to map a button that will allow a switch between the created profiles. Maybe an option to allow a notification of a successful profile change. Like "'Build' mode" "'Explore' mode" popping up on the upper right hand corner. I can even see the alternative and the main suggestion being done together.

**Additional context**
NA

**Comment by CasperH2O** [comment] 2023-10-30 04:41
There are short term plans to make sub profiles, for example for emulators that all have the same executable but people play different games. This could also potentially be used for different gamepad layouts, it will allow changing quickly through quicktools.

Alternatively, people have been asking for multi layered controller schemes.

**Comment by CasperH2O** [comment] 2023-10-30 12:12
Closing this, as this is either a duplicate of #792 or #796 depending on the implementation.

**Closed by CasperH2O** 2023-10-30 12:12 UTC
Labels: enhancement
