### ISSUE TITLE
Default profile gets a profile path on version 0.15.X

### ISSUE THREAD

**Issue by jordansoper** [Valkirie/HandheldCompanion#401] opened 2023-03-16 21:51 UTC
Default Profile is auto-creating a profile path for whatever application is open in the background, rendering the system unable to start.

This is preventing the gyro controls from working.

Have tested by reverting back to 0.14.X, the issue is not present

**Comment by CasperH2O** [comment] 2023-03-17 07:08
@jordansoper do you mean something like this? Mine goes to text input host.

![afbeelding](https://user-images.githubusercontent.com/14330834/225836277-01b81f2a-0838-4e7c-9512-888fef8ebba5.png)

**Comment by jordansoper** [comment] 2023-03-17 07:42
yes, correct, the profile path will change depending on what you what doing before opening HC

**Comment by Valkirie** [comment] 2023-03-18 08:53
I have no idea how to replicate this issue.

**Comment by CasperH2O** [comment] 2023-03-19 08:11
@jordansoper I tried reproducing this after it had happened on my machine but was unable to. So I can confirm the issue, just no clue as to the cause.

As a workaround you can close HC, delete the default profile and start HC again. It will be recreated without the path (on my machine did).

**Comment by Valkirie** [comment] 2023-03-19 12:49
A fix is in the work to prevent default profile from actually losing its default status.

**Comment by CasperH2O** [comment] 2023-03-22 09:16
Fix implemented, seems to work, unable to reproduce. Will be part of upcoming release.

**Closed by CasperH2O** 2023-03-22 09:16 UTC
Labels: bug
