### ISSUE TITLE
Auto TDP System Instability

### ISSUE THREAD

**Issue by nixtar** [Valkirie/HandheldCompanion#603] opened 2023-06-01 13:49 UTC
Hi,

I've just started trying HC's Auto TDP and since doing so I've experienced 2 crashes in the space of about 90 minutes.

Both times were while running yuzu emulator, one was a full system lock up and the other was a bsod. I didn't get time to take a photo of the bsod with an amd related driver listed.

I've been running other Auto TDP solutions such as Hyatice's AutoPerf bat with the same game via yuzu for many, many hours without any issues.

I'm wondering if HC's implementation is flying slightly too close to the sun in regards to how aggressively its adjusting things?

I'll try and keep this post updated with any further details as I'm able to test more games etc.

Please let me know if there is anything in particular I can try.

**Comment by CasperH2O** [comment] 2023-06-01 14:48
Thank you, I'll have a look at Yuzu.

**Comment by nixtar** [comment] 2023-06-02 10:03
Happy to provide more details about the yuzu setup, just not sure if we want to discuss emulation of a particular companies console here..

I'm Nick#5344 on discord if you want to hit me up outside of this repo.

I also noticed that yuzu did update when I used it with auto Tdp last. I'll try and put a few more hours on it with a static tdp set and see how it goes.

Hopefully it's just a red herring but I wanted to log it just in case anyone else was having stuff like this happen.

I'll keep you posted.

**Comment by nixtar** [comment] 2023-06-03 09:47
Some more data.

Played for an hour without HC without issues.
Then I launched HC and within minutes the system hung up.

However this time I had a detailed custom overlay running and could see that when it hung the tdp on the cpu was reporting 5.2 watts and the usage was only about 2% across the gpu and cpu.
I went into HC and set the minimum tdp from 5 to 6 and was able to play for a another hour without issues.

Could have just gotten lucky, I'll spend some more time with it tomorrow.

Not sure if it could be related, but in hwinfo the epp % doesn't match what is configured in HC. (50% in HC translates to 33% in hwmonitor) If I set the epp in Ciphrays bat the % match.

**Comment by CasperH2O** [comment] 2023-06-03 10:05
> However this time I had a detailed custom overlay running and could see that when it hung the tdp on the cpu was reporting 5.2 watts and the usage was only about 2% across the gpu and cpu.
I went into HC and set the minimum tdp from 5 to 6 and was able to play for a another hour without issues.

Here we go, there have been two reports about instability with AutoTDP, yours and another. The other one was also on a GPD Win, with a lower limit of 5. I made the recommendation there also to set it to 6 or 7. 

However, other users reported that with manual TDP control, they can even set it to 3 or 4.

**Comment by nixtar** [comment] 2023-06-03 11:28
Yeah, suspect maybe I didn't win the silicon lottery. 😋

I have played about 10 hours of retro games at 4 watts (statically) without issues, I wonder if it's going from ~18 watts to 5 quickly and with the core temps being higher etc.

I'll keep it on 6 and keep the thread posted. If it's resolved for my device at 6-7 watts then I'll close it off.

**Comment by CasperH2O** [comment] 2023-06-08 07:55
@nixtar I've received a log from another user who had this issue (but on a SteamDeck). In that log I found the setting of TDP returned a -4 error code. 

Could you share your HC logfiles from the time/date of the crash? They can be found in /programfiles/handheldcompanion/logs

**Comment by CasperH2O** [comment] 2023-06-08 08:02
Ok, digging through ryzen adj it seems an error code 4 means SMU_REJECTED. A SMU is probably a Source Measure Unit (https://en.wikipedia.org/wiki/Source_measure_unit).

https://github.com/FlyGoat/RyzenAdj/blob/f6fbf9d17f70d9736bc8294ccd8438ae94804aa9/lib/ryzenadj.h#L58

No idea what to do with that though, do we wait, reset something, reboot the device etc?

FYI @Valkirie

**Comment by Casao** [comment] 2023-06-08 13:27
@CasperH2O I believe SMU in the ryzen context is "System Management Unit", which is what Ryzen Master uses to control the chips (probably other apps as well?)

@nixtar I've had great success on my Win4 after installing Hyatice's power profile, it's a modified power saver profile that specifically mentions improved AutoTDP support. I grabbed it from the HCP repo, though it's available in various places. Since doing that, I have not had a driver lockup, and I run HC 24/7.

**Comment by CasperH2O** [comment] 2023-06-08 14:09
From the logs, it seems the -4 error occured when the timing between TDP requests was 0.998 instead of the usual 1.000. It seems 0.999 also occurs quite often. To be on the safe side, I'll increase the AutoTDP timer with 10 msec.

Additionally, I'll only call setting AutoTDP in case the TDP has actually changed... Normally with AutoTDP that happens all the time, but if it reaches the lowest or max TDP, it may as well stop requesting the SMU.

**Comment by nixtar** [comment] 2023-06-08 14:14
Sorry for being a bit MIA on this issue.

I recently replaced the ssd and didn't bother to backup the old os so I don't have the logs any more.
I'll reproduce the crashes again and upload the logs when I get a chance.

@Casao thanks for the tip, I'll give that a try once I've done been able to consistently reproduce the issue again.

**Comment by CasperH2O** [comment] 2023-06-08 14:50
> I'll reproduce the crashes again and upload the logs when I get a chance.

That would be great @nixtar , I've already made some changes, can I make you a special build tomorrow for you to test instead of the latest release?

**Comment by CasperH2O** [comment] 2023-06-09 06:08
@nixtar no need to test the stability for now, we found the actual reason that needs improving. Although my improvements will probably reduce the chance of it occurring, it's not a fix.

The SMU sometimes can't handle it when we send more then one command at the same time, there needs to be a minimum of 10 msec between each. So we need to put some time between setting slow, fast and stapm.

**Comment by CasperH2O** [comment] 2023-06-12 09:29
@Valkirie I'd like to add a 12 msec time delay in this for loop, the one that AutoTDP uses to set the three power types:

https://github.com/Valkirie/HandheldCompanion/blob/b1981a3c0543bab076e27fd27eca8cd8aff2c3a7/HandheldCompanion/Managers/PerformanceManager.cs#L481

According to @JamesCJ60  this should prevent the SMU from locking up and throwing an error.  

What is your preferred way of adding such a delay? A Thread.Sleep or Task.Delay or something else?

**Comment by Valkirie** [comment] 2023-06-12 10:04
> @Valkirie I'd like to add a 12 msec time delay in this for loop, the one that AutoTDP uses to set the three power types:
> 
> https://github.com/Valkirie/HandheldCompanion/blob/b1981a3c0543bab076e27fd27eca8cd8aff2c3a7/HandheldCompanion/Managers/PerformanceManager.cs#L481
> 
> According to @JamesCJ60 this should prevent the SMU from locking up and throwing an error.
> 
> What is your preferred way of adding such a delay? A Thread.Sleep or Task.Delay or something else?

try await task.delay(xxx)

**Comment by CasperH2O** [comment] 2023-06-13 06:41
Initial update in this PR #618.

Adjusted several timers, removed unnecessary setting of TDP and put in time between setting of slow, fast and stapm.

**Comment by nixtar** [comment] 2023-06-13 12:03
My 2c,

Adding async will have a cost due to the state machine that gets created to manage everything, this will lead to more allocations etc. But it will add more instructions on the cpu and worst case cause another thread to be used from the pool.

As the app is targeting low tdp devices, and this feature in particular is designed to squeeze every milliwatt of efficiency out of them. Might be worth eating the blocked thread that thread.sleep causes?
If the sleeps have too big of an impact on the GUI it might be worth sticking all of this in its own thread? I haven't dug too deep into the architecture of this code base so sweeping statements like that should be taken with some grains of salt. 😄 

I've done some benchmarks 😃
``` ini
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1702/22H2/2022Update/SunValley2)
13th Gen Intel Core i7-13700K, 1 CPU, 24 logical and 16 physical cores
.NET SDK=7.0.203
  [Host]    : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  RyuJitX64 : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2

Job=RyuJitX64  Jit=RyuJit  Platform=X64  
```
|       Method | LoopTimes |        Mean |    Error |   StdDev | Code Size | Allocated |
|------------- |---------- |------------:|---------:|---------:|----------:|----------:|
| **Thread_Sleep** |        **10** |    **126.2 ms** |  **0.56 ms** |  **0.52 ms** |     **190 B** |     **150 B** |
|   Task_Delay |        10 |    123.7 ms |  0.61 ms |  0.57 ms |     501 B |    2166 B |
| **Thread_Sleep** |       **100** |  **1,258.2 ms** |  **4.37 ms** |  **3.88 ms** |     **246 B** |     **600 B** |
|   Task_Delay |       100 |  1,241.4 ms |  5.28 ms |  4.94 ms |     246 B |   30832 B |
| **Thread_Sleep** |      **1000** | **12,567.1 ms** | **17.32 ms** | **15.36 ms** |     **246 B** |     **600 B** |
|   Task_Delay |      1000 | 12,386.2 ms | 16.14 ms | 15.10 ms |     246 B |  182032 B |


BenchmarkDotNet code:
```c#
[MemoryDiagnoser(false)]
[DisassemblyDiagnoser(printSource: true)]
[RyuJitX64Job]
public class SleepBenchmarks
{
    [Params(10, 100, 1000)]
    public int LoopTimes;

    [Benchmark]
    public void Thread_Sleep()
    {
        for (int i = 0; i < LoopTimes; i++)
        {
            Thread.Sleep(12);
        }
    }
    
    [Benchmark]
    public async Task Task_Delay()
    {
        for (int i = 0; i < LoopTimes; i++)
        {
            await Task.Delay(12);
        }
    }
}
```

Unfortunately, I wasn't able to get the HardwareCounters working in BenchmarkDotNet, but the CPU usage was slightly higher while it was running the Task_Delay benchmark.

## .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
```assembly
; SleepBenchmarks.SleepBenchmarks.Thread_Sleep()
       push      rbp
       sub       rsp,70
       lea       rbp,[rsp+70]
       xor       eax,eax
       mov       [rbp-3C],eax
       mov       [rbp+10],rcx
;         for (int i = 0; i < LoopTimes; i++)
;              ^^^^^^^^^
       xor       ecx,ecx
       mov       [rbp-3C],ecx
       mov       dword ptr [rbp-48],3E8
       jmp       short M00_L01
;             Thread.Sleep(12);
;             ^^^^^^^^^^^^^^^^^
M00_L00:
       mov       ecx,0C
       call      qword ptr [7FFDA0727708]; System.Threading.Thread.Sleep(Int32)
       mov       eax,[rbp-3C]
       inc       eax
       mov       [rbp-3C],eax
M00_L01:
       mov       ecx,[rbp-48]
       dec       ecx
       mov       [rbp-48],ecx
       cmp       dword ptr [rbp-48],0
       jg        short M00_L02
       lea       rcx,[rbp-48]
       mov       edx,0F
       call      CORINFO_HELP_PATCHPOINT
M00_L02:
       mov       ecx,[rbp-3C]
       mov       rax,[rbp+10]
       cmp       ecx,[rax+8]
       jl        short M00_L00
       add       rsp,70
       pop       rbp
       ret
; Total bytes of code 98
```
```assembly
; System.Threading.Thread.Sleep(Int32)
       push      rdi
       push      rsi
       push      rbx
       sub       rsp,20
       mov       esi,ecx
       cmp       esi,0FFFFFFFF
       jl        short M01_L00
       mov       ecx,esi
       call      System.Threading.Thread.SleepInternal(Int32)
       nop
       add       rsp,20
       pop       rbx
       pop       rsi
       pop       rdi
       ret
M01_L00:
       mov       rcx,offset MT_System.Int32
       call      CORINFO_HELP_NEWSFAST
       mov       rdi,rax
       mov       [rdi+8],esi
       mov       rcx,offset MT_System.ArgumentOutOfRangeException
       call      CORINFO_HELP_NEWSFAST
       mov       rsi,rax
       mov       ecx,13C5
       mov       rdx,7FFDA04D4000
       call      CORINFO_HELP_STRCNS
       mov       rbx,rax
       mov       ecx,0A079
       mov       rdx,7FFDA04D4000
       call      CORINFO_HELP_STRCNS
       mov       rcx,rax
       call      qword ptr [7FFDA074D030]
       mov       r9,rax
       mov       rdx,rbx
       mov       r8,rdi
       mov       rcx,rsi
       call      qword ptr [7FFDA08B5780]
       mov       rcx,rsi
       call      CORINFO_HELP_THROW
       int       3
; Total bytes of code 148
```

## .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
```assembly
; SleepBenchmarks.SleepBenchmarks.Task_Delay()
       push      rbp
       sub       rsp,40
       lea       rbp,[rsp+40]
       vxorps    xmm4,xmm4,xmm4
       vmovdqa   xmmword ptr [rbp-20],xmm4
       vmovdqa   xmmword ptr [rbp-10],xmm4
       mov       [rbp+10],rcx
       call      qword ptr [7FFDA0AD1438]; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Create()
       mov       [rbp-10],rax
       mov       rcx,[rbp+10]
       mov       [rbp-20],rcx
       mov       dword ptr [rbp-18],0FFFFFFFF
       lea       rcx,[rbp-10]
       lea       rdx,[rbp-20]
       call      qword ptr [7FFDA0AD15A0]; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[SleepBenchmarks.SleepBenchmarks+<Task_Delay>d__2, SleepBenchmarks]](<Task_Delay>d__2 ByRef)
       lea       rcx,[rbp-10]
       call      qword ptr [7FFDA0AD14B0]; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.get_Task()
       nop
       add       rsp,40
       pop       rbp
       ret
; Total bytes of code 84
```
```assembly
; System.Threading.Tasks.Task.GetAwaiter()
       mov       rax,rcx
       ret
; Total bytes of code 4
```
```assembly
; System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       mov       rcx,[rcx]
       mov       eax,[rcx+34]
       and       eax,11000000
       cmp       eax,1000000
       jne       short M02_L00
       ret
M02_L00:
       jmp       qword ptr [7FFDA0AD13C0]; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
; Total bytes of code 25
```
```assembly
; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Create()
       xor       eax,eax
       ret
; Total bytes of code 3
```
```assembly
; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[SleepBenchmarks.SleepBenchmarks+<Task_Delay>d__2, SleepBenchmarks]](<Task_Delay>d__2 ByRef)
       push      rbp
       sub       rsp,20
       lea       rbp,[rsp+20]
       mov       [rbp+10],rcx
       mov       [rbp+18],rdx
       mov       rcx,[rbp+18]
       call      qword ptr [7FFDA0AD1660]; System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[SleepBenchmarks.SleepBenchmarks+<Task_Delay>d__2, SleepBenchmarks]](<Task_Delay>d__2 ByRef)
       nop
       add       rsp,20
       pop       rbp
       ret
; Total bytes of code 35
```
```assembly
; System.Runtime.CompilerServices.AsyncTaskMethodBuilder.get_Task()
       mov       rax,[rcx]
       test      rax,rax
       je        short M05_L00
       ret
M05_L00:
       lea       rax,[7FFDFFFDD648]
       jmp       qword ptr [rax]
; Total bytes of code 19
```
```assembly
; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
       push      rsi
       sub       rsp,20
       mov       rsi,rcx
       test      dword ptr [rsi+34],1600000
       jne       short M06_L00
       mov       rcx,rsi
       xor       r8d,r8d
       mov       edx,0FFFFFFFF
       call      qword ptr [7FFDFFFDBA60]; Precode of System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
M06_L00:
       mov       rcx,rsi
       call      qword ptr [7FFDFFFDB840]; Precode of System.Threading.Tasks.Task.NotifyDebuggerOfWaitCompletionIfNecessary()
       mov       ecx,[rsi+34]
       and       ecx,1600000
       cmp       ecx,1000000
       je        short M06_L01
       mov       rcx,rsi
       call      qword ptr [7FFDFFFDD738]
M06_L01:
       nop
       add       rsp,20
       pop       rsi
       ret
; Total bytes of code 76
```

**Comment by Valkirie** [comment] 2023-06-13 12:05
Well, if you're into optimization, I'd love to get some external eye on the overall project. Also feel free to submit pull request for anything you've tested and see as a performance improvement. Also, feel free to raise on hand on Discord :)

**Comment by nixtar** [comment] 2023-06-13 12:06
> Initial update in this PR #618.
> 
> Adjusted several timers, removed unnecessary setting of TDP and put in time between setting of slow, fast and stapm.

Ahh I see this was posted before I finished my tldr. :) (Can you tell I'm a backend dev who obsesses over micro-optimisations? xD)

The way you are implementing async void and never awaiting it, this will block the calling thread anyway. So IMO unless we implement async all the way from the top down, Task.Delay is the way.

**Comment by Valkirie** [comment] 2023-06-13 12:18
Pleasant to hear ! I am no programmation expert so I'm basically learning on the go.

**Comment by CasperH2O** [comment] 2023-06-28 10:00
@nixtar the improvement has been out for a few days, I've heard to no new reports on BSODs or system crashes. Are you able to reproduce this issue with the latest release 0.16.2.2?

**Comment by nixtar** [comment] 2023-06-29 08:43
Sorry for being MIA. I've unfortunately had no mental capacity to do any gaming in the past few weeks.

I'm hoping to kick back this weekend. I'll let you know. 👍

**Comment by CasperH2O** [comment] 2023-07-10 06:08
I'm closing this one, I've had no further reports of crashes and no logs with errors on TDP setting. I think our solutions worked.

**Closed by CasperH2O** 2023-07-10 06:08 UTC
Labels: bug
