### ISSUE TITLE
Endless vibrate on startup

### ISSUE THREAD

**Issue by thienntm** [Valkirie/HandheldCompanion#776] opened 2023-09-06 04:39 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [X] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
rog ally

**Handheld Companinion Version**
0.18.0.1b

**Describe the bug**
Endless vibrate on startup, causing lag and high memory. Restart the ally does not do the job, still vibrating during restart process and stopped after logged in to windows and HC auto start again.

**To Reproduce**
1. Go to 'Setting'
2. Toggle on 'Auto-start application'
3. Toggle on 'Open application in background'
4. Toggle on 'Close minimizes'
5. Go to 'Controller'
6. Toggle on 'Vibrate controller on connect'
6. Restart ally and see error

**Expected behavior**
Short vibrate and stop

**Screenshots**
No screenshot

**Logs file**
Will be add log later

**Comment by thienntm** [comment] 2023-09-13 02:11
> I have noticed the vibration taking slightly longer (2 seconds?) on the latest release with my ROG Ally, but I cannot reproduce your issue as is.
> 
> Are you starting/booting anything else? Do you use a kind of start up manager? You mention lag and high memory, how much memory is HC using?

Hi, I only set steam big picture mode at booting. At first, I thought it caused by steam, but after move from steam to playnite fullscreen mode, the issue still there. 
This morning, I tried to disable auto start at boot to start it manually. After reboot device and everything has started, I manual start HC but it continue endless vibrate, it seems that the error is not due to auto start.

Before, I was in double input problem, like this issue [https://github.com/Valkirie/HandheldCompanion/issues/770](770). In hidhide config show 2 controller, then I tick the second one and the issue has fixed. I have no idea if the vibrate issue related to this

**Comment by CasperH2O** [comment] 2023-09-13 05:46
@thienntm not a solution, but as a workaround you could untick the vibrate controller on connect option on the controller page.

**Comment by thienntm** [comment] 2023-09-15 06:19
> @thienntm not a solution, but as a workaround you could untick the vibrate controller on connect option on the controller page.

Hi @CasperH2O , after a few day test, I'm sure my issue relate to double input in hidhide like this [https://github.com/Valkirie/HandheldCompanion/issues/770](url). I tick the second one to disable and restart device and boom, endless vibrate.

**Comment by sr1canskhsia** [comment] 2023-09-18 03:46
Just updated HC to the latest version (0.18.0.3) and started having the same issue. Device is ASUS Rog Ally. Also tried a complete clean install of HC but the issue is still there.

**Comment by Valkirie** [comment] 2023-09-18 07:25
Will look into it today

**Comment by azodev** [comment] 2023-10-06 10:33
Same here on rog ally (with MCU 313 update)

**Comment by NightHammer1000** [comment] 2023-10-21 19:07
Same here on OneXPlayer 2 Pro

**Comment by Valkirie** [comment] 2023-10-21 19:08
It's fixed on forthcoming update. In the meantime, disable vibrate on connect.

**Comment by NightHammer1000** [comment] 2023-10-21 19:09
> disable vibrate on connect.

Does not help in my case. But thanks for the info.

**Comment by CasperH2O** [comment] 2023-11-18 07:54
This issue has been fixed for "all" devices. There was indeed a bug in HC that caused this at times.

On that note AOKZOE and OneXPlayer have a different issue, reported here: #818 

Closing as fixed.

**Closed by CasperH2O** 2023-11-18 07:54 UTC
Labels: bug
