### ISSUE TITLE
When waking up from sleep, only the mouse works, not the controller

### ISSUE THREAD

**Issue by ARguy15** [Valkirie/HandheldCompanion#388] opened 2023-03-08 15:58 UTC
Hi.

When I put the steam deck on sleep for a while, the controller does not work when waking up the device.
If it goes to sleep and after 2 minutes I wake it up, the controller works fine. 
If left overnight, when I wake it, the mouse works fine but the controller itself does not work.
I am running Windows 11 Pro. 

To get it to work I have to either restart the service or exit/open the application again.

I havent tried yet using Net Start from cmd or creating an event in the scheduler to restart it from sleep.

Idk if this would help but the issue happened with Steam Deck Tools as well but not SWICD. 

Thank you

**Comment by Valkirie** [comment] 2023-03-08 16:04
Thanks for sharing the issue. I'll definitely make it a top priority to get this issue addressed before releasing 0.15 publicly.

**Comment by CasperH2O** [comment] 2023-03-17 06:51
@ARguy15 several improvements and fixes have been made for waking from sleep in the latest release (0.15.0.3) can you check and confirm you still have this problem?

**Comment by Havner** [comment] 2023-04-01 14:24
I can still confirm it on SteamDeck on 0.15.0.4 (using XBox controller, it might be important). It doesn't happen for a short sleep, but when the device sleeps for like a day and the wakeup is a longer process with windows bootup screen (when it hibernates due to prolonged sleep? no sure).

Mouse/keyboard works, controller doesn't.

One more thing I noticed is that when after such a sleep you disconnect the controller and connect it again (in HC) you can see two controllers in the joy.cpl. So it somehow looks like the process lost the connection with the original controller (vigem api?) and cannot even disconnect it. Although restarting the app altogether removes the stale one.

**Comment by Havner** [comment] 2023-04-03 13:27
Happened again. Xbox controller did not respond after ~12h of sleep. When I disconnected it and connected it again it wasn't able to remove the stale one. It added a new one. The new one works.

Restarting HC cleans up the stale one and everything is fine again.

![xbox-stopped-responding](https://user-images.githubusercontent.com/6246347/229523118-90082481-3d0c-4eb5-92c5-c0adefdf2a72.png)

**Comment by Valkirie** [comment] 2023-04-03 14:47
I'll work on it :)

**Comment by Havner** [comment] 2023-04-03 14:57
> Are you also getting that issue by "simply" putting the device into Hybernation (not sleep) ?

I did 5 consecutive hibernations and it worked every single time. Also it doesn't always happen even when the hibernation seems to be triggered by long sleep.

So either it's random or it's time related. Not sure.

**Comment by Valkirie** [comment] 2023-04-03 15:02
Just to make sure I understand, you can't reproduce the problem with short or relatively short hibernations. On the other hand, long hibernations almost always trigger the problem?

**Comment by Havner** [comment] 2023-04-03 15:06
I cannot reproduce it with short manually triggered hibernations, yes.

About long hibernations I've never measured them. When I wake up steam deck I can see whether it entered hibernation (because the system boots up with a windows logo), but even then **it doesn't always happen**. That's why I said, that it's either random or it requires particularly long hibernation (like >12h). I have too little data to answer that with confidence.

**Comment by Valkirie** [comment] 2023-04-03 15:24
>   Hotkeys work (like desktop profile switching) and keyboard/mouse mappings do work as well. Only the controller mappings don't.

Do you mean you can move mouse and send keyboard inputs using joysticks and buttons (ie: using the Desktop layout) ?

**Comment by Havner** [comment] 2023-04-03 15:36
Yes. Catching SteamDeck controller inputs works properly. Sending mouse/keyboard events also works properly. Only sending XBox 360 events doesn't. The other user mentioned he's using DS4 so it doesn't seem related only to vigem.

**Comment by IstanbulRed** [comment] 2023-04-03 20:27
I was using my Steamdeck tonight.

I pressed the power button once to send the device to sleep. I left the device for almost exactly 20 minutes. When Windows resumed. Controller was present in the windows controller list but not working. All other HC hotkeys were working.

**Comment by Valkirie** [comment] 2023-04-03 20:47
> 

Hotkeys that were mapped to controller buttons ?

**Comment by IstanbulRed** [comment] 2023-04-05 08:46
> > 
> 
> Hotkeys that were mapped to controller buttons ?

Yes sir. Hotkeys mapped to Steamdecks controller buttons worked fine. For example, I have the lizard mouse and buttons set to the physical steamdeck back buttons. All of these worked fine.

In Windows controllers, I then had 2 USB controllers present ie sent from handheld companion, but these did not work.

**Comment by CasperH2O** [comment] 2023-06-29 19:20
@IstanbulRed we just released 0.16.2.3 which adressed a couple of controller issues related to hibernate, can you check if this is still an issue?

**Comment by CasperH2O** [comment] 2023-11-23 13:39
No feedback from original ticket creator, issue has not been reported since. Closing ticket.

**Closed by CasperH2O** 2023-11-23 13:39 UTC
Labels: bug
