### ISSUE TITLE
ROG Ally OEM buttons to support press and hold

### ISSUE THREAD

**Issue by arondesign** [Valkirie/HandheldCompanion#731] opened 2023-07-18 22:20 UTC
When remapping the "Command Center" and "Armory Crate" buttons, the interaction is not working as expected.
- On button press start, the buttons do nothing.
- On button press end, the buttons send a quick "press" action, then immediate depress action. While this does send the correct command, the interaction like this makes press and hold interactions impossible to achieve (and since it only triggers a press on touch end, it makes the actual button press somewhat latent).
- "Hold to Repeat" does not work at all.

**Comment by CasperH2O** [comment] 2023-07-19 07:36
@arondesign you are describing exactly how they are currently expected to behave. The ROG Ally buttons are a new type of button for HC (using a seperate HID device). This can definitely be improved. Do you have any C# experience, we could always use help with this?

**Comment by CasperH2O** [comment] 2024-05-17 18:53
Closing as duplicate of #942

**Closed by CasperH2O** 2024-05-17 18:53 UTC
Labels: Enhancement
