### ISSUE TITLE
DS4 Virtual controller not showing after trying to use flydigi apex 2 with their flydigi space program

### ISSUE THREAD

**Issue by markmarkmrk** [Valkirie/HandheldCompanion#789] opened 2023-10-02 23:43 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [x] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Aokzoe A1 Pro

**Handheld Companinion Version**
0.18.0.3 also 0.18.0.1

**Describe the bug**
I cannot emulate DS4. No emulation shows up. Xbox 360 works fine.

**To Reproduce**
Everything was fine BEFORE i tried to use my old flydigi apex 2 controller. It has a usb connector that I can plug along with their Flydigi space windows program. When I was trying to install, it prompted me to upgrade the dongle (since this is a windows 11 probably) eventually failed. Tried to use their cable, but to no avail. Decided to stick with Aokzoe built in controller. Restarted AOKZOE, opened HC, and i tried to emulate DS4, it didn't work. Below the Input device section, Controller (One-Xbox), Sony Interactive Entertainment DualSense Wireless Controller showed up with the orange loading bar below it. It cannot connect anymore. Was advised to downgrade to 0.18.0.1, but cannot emulate same issue since the xbox only shows up. 

Heres the initial video before I downgraded to 0.18.0.1

https://github.com/Valkirie/HandheldCompanion/assets/146787400/fe310ce1-23dd-4a3b-8b47-aad03f95e526

I don't know where to find the log file

**Comment by CasperH2O** [comment] 2023-10-04 06:32
We've been troubleshooting this problem a bit on Discord. It's an odd one. Best to wait for 0.18.0.4 which includes some improved connectivity code.

**Comment by CasperH2O** [comment] 2024-01-10 13:03
@markmarkmrk do you still have this issue with a more recent HC, the controller manager was seriously updated and I don't have a FlyDigi to test and try this with myself.

**Comment by CasperH2O** [comment] 2024-01-17 11:50
Original issue reporter has not provided feedback as requested, unable to reproduce as none the of HC developers have a FlyDigi. Closing, @markmarkmrk if you want to reopen this issue feel free to do so.

**Closed by CasperH2O** 2024-01-17 11:50 UTC
Labels: bug
