### ISSUE TITLE
Touchscreen Stopped

### ISSUE THREAD

**Issue by GamzMaka12** [Valkirie/HandheldCompanion#899] opened 2023-12-21 12:18 UTC
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ X] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [ ] LENOVO

**Device model**
ROG Ally Z1E

**Handheld Companinion Version**
0.19.1.8

**Describe the bug**
So, I had went to uninstall Handheld Companion (and undo my Smokeless mod, as power limits didn't hold up and my CPU speeds kept being shot down to 1GHz *while playing*), and as I did, and uninstalled the other software, upon reboot, my touchscreen stopped working, as did my USB C, so I had to do a cloud restore.

**To Reproduce**
1. Uninstall

If anyone wants to help me set this up so this doesn't happen again and my CPU doesn't rank and my games lag after 10 minutes, be my guest.

**Comment by CasperH2O** [comment] 2023-12-21 13:17
To our knowledge HC doesnt do anything with the touch screen nor its drivers nor the USB C ports. 

Are you sure this was caused by HC and not Smokeless, a BIOS mod?

**Comment by GamzMaka12** [comment] 2023-12-22 08:52
I'm entirely sure as I only had this issue upon restart after uninstalling HC. It's due to making input virtualized. I installing it took it all away from me.

**Comment by GamzMaka12** [comment] 2023-12-22 08:54
I'd really like to get more juice out of my ROG since I saw the performance uplift, just, afraid to now with these issues. My main issue was the fact my CPU kept bugging out and wouldn't run at full speed when I played a game, specifically a game, nothing more. Desktop it ran full speed.

**Comment by Bladen123** [comment] 2024-01-14 01:57
Yes this is true , i had this problem too and this DEV is just a MothaFuka becasue he still update this dumb HC app and fuck us up to complete remove windows /savegames/Games and all shit from ally just becasue 1 time installed and uninstalled the HC

**Comment by CasperH2O** [comment] 2024-01-14 04:54
@Bladen123 the issue you describe is discussed here: https://github.com/Valkirie/HandheldCompanion/issues/817

**Comment by CasperH2O** [comment] 2024-02-04 20:54
This issue is most likely a duplicate of #817 which has been fixed.

**Closed by CasperH2O** 2024-02-04 20:54 UTC
Labels: bug
