### ISSUE TITLE
ROG Ally sleep loses access to physical controller

### ISSUE THREAD

**Issue by electronicrice** [Valkirie/HandheldCompanion#642] opened 2023-06-22 03:27 UTC
Anytime the ROG Ally goes to sleep, when it wakes back up HC can no longer see the physical controller and input won't work. HC has to be completely closed out and reopened, and the service restarted for the controller to show back up.

**Comment by CasperH2O** [comment] 2023-06-22 06:07
Can confirm, it's being investigated. Thank you for reporting.

**Comment by trippyone** [comment] 2023-06-23 01:41
Seems to be caused by HidSharp library. The code will hang for long time on this function, fail, and will eventually loop. This will repeat for minutes until eventually it works.

https://github.com/Valkirie/HandheldCompanion/blob/dc041984b68242f7b0cda54305fb106d5b4c4f7c/ControllerCommon/Devices/ASUS/ROGAlly.cs#L89C5-L89C5

The reason why it's not working is unknown, I can't step in the function to analyze the issue. Hopefully it helps you guys find the exact cause :)

**Comment by CasperH2O** [comment] 2023-06-23 08:24
Fixed. Tested on ROG Ally. Could use another tester though @trippyone , can you try also just to be 100% sure? It's the FixControllerResume branch.

**Comment by Valkirie** [comment] 2023-06-23 08:52
> Fixed. Tested on ROG Ally. Could use another tester though @trippyone , can you try also just to be 100% sure? It's the FixControllerResume branch.

Merged the branch into main because it no longer has any regressions anyway.

**Comment by trippyone** [comment] 2023-06-23 11:50
Confirmed that the issue is resolved.

**Comment by trippyone** [comment] 2023-06-28 01:17
see PR above. hopefully this fixes it.

**Comment by trippyone** [comment] 2023-06-28 19:18
Another and hopefully final attempt to fix the OEM keys not working on wake up issue. We need testers. @CasperH2O

**Comment by electronicrice** [comment] 2023-06-28 19:55
> Another and hopefully final attempt to fix the OEM keys not working on wake up issue. We need testers. @CasperH2O

I'm open to test. Just let me know

-eRice

**Comment by CasperH2O** [comment] 2023-06-28 19:57
@electronicrice are you on Discord, we are testing there?

**Comment by electronicrice** [comment] 2023-06-28 20:04
> @electronicrice are you on Discord, we are testing there?

Yep, I'm eRice (.electronicrice) on discord

**Comment by CasperH2O** [comment] 2023-06-29 19:15
@electronicrice I think we can close this one?

**Comment by electronicrice** [comment] 2023-06-29 19:58
I think so!

**Closed** 2023-06-30 04:19 UTC
Labels: bug
